public enum EventTriggerType
{
    UNDEFINED = -1, LIKE = 0, LIKE_DELETE = 1, PUBLISHED_ARTICLE = 2,
    FOLLOW_USER = 3, UNFOLLOW_USER = 4, SPECIAL_REWARD = 5, STORY_POINTS_NOTIFICATION = 6,
    FCM_TEST_MESSAGE = 7, WEEKLY_REWARD_MANUAL_TRIGGER = 8,  TERMINATE_ACCOUNT = 9, LIKE_COMMENT = 10, LIKE_COMMENT_DELETE = 11,
    REPLY_COMMENT = 12, WRITE_COMMENT = 13, REMOVE_ARTICLE = 14, WRITE_MESSAGE = 15, NEW_MESSAGE_NOTIFIATION = 16
}