public enum TransactionDescriptionType{
    LIKE_RECEIVED = 0,
    FIRST_POST_REWARD = 1,
    FIRST_LIKE_RECEIVED_REWARD = 2,
    FIRST_LIKE_SENT_REWARD =  3,
    REWARD_CLAIMED = 4,
    FIRST_FOLLOW = 5,
    
    FOLLOW_RECEIVED = 6,
    SPECIAL_REWARD = 7,
    COMMENT_LIKE_REWARD = 8,
    COMMENT_REPLY_REWARD = 9,
    COMMENT_RECEIVED_REWARD = 10,
    NONE = 99,
}